version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  labels:
  - dependabot
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.41
    - 15.0.0
  - dependency-name: next-pwa
    versions:
    - 5.2.1
    - 5.2.14
  - dependency-name: "@storybook/react"
    versions:
    - 6.2.4
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.2.4
  - dependency-name: next
    versions:
    - 10.1.3
